# Minimal solver configuration for testing

[solver]
id = "oif-solver-test"
monitoring_timeout_minutes = 5

# Networks with WETH tokens (more likely to be deployed)
[networks.11155111]
rpc_url = "https://ethereum-sepolia-rpc.publicnode.com"
input_settler_address = "0xcA919F1EeAA377009E11a5C5c9FA5923fC3eD563"
output_settler_address = "0x331B0c3b82C8C3CF06DFD2a12905Cc311589FB6D"
[[networks.11155111.tokens]]
address = "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14"
symbol = "WETH"
decimals = 18

[networks.421614]
rpc_url = "https://sepolia-rollup.arbitrum.io/rpc"
input_settler_address = "0xCe81010d0A47FF13Cc19105E8Ef7B597aA8D3460"
output_settler_address = "0x92DAe04879b394104491d5153C36d814bEbcB388"
[[networks.421614.tokens]]
address = "0x980B62Da83eFf3D4576C647993b0c1D7faf17c73"
symbol = "WETH"
decimals = 18

[storage]
primary = "memory"
cleanup_interval_seconds = 3600
[storage.implementations.memory]

[account]
primary = "local"
[account.implementations.local]
private_key = "0xd32b4f4ee569fefe3caa3bce14a7504de18b6153feecb4672734b818e79220d7"

[delivery]
min_confirmations = 1
[delivery.implementations.evm_alloy]
network_ids = [11155111, 421614]

[discovery]
[discovery.implementations.onchain_eip7683]
network_ids = [11155111, 421614]

[order]
[order.implementations.eip7683]
[order.strategy]
primary = "simple"
[order.strategy.implementations.simple]
max_gas_price_gwei = 100

[settlement]
[settlement.domain]
chain_id = 1
address = "0x0000000000000000000000000000000000000000"
[settlement.implementations.eip7683]
network_ids = [11155111, 421614]
oracle_addresses = { 11155111 = "0xa39434521088d9a50325BC50eC2f50660e06Df34", 421614 = "0x7711d06A5F6Fc7772aa109D2231635CEC3850dBa" }
dispute_period_seconds = 1

[api]
enabled = true
host = "0.0.0.0"
port = 3000
timeout_seconds = 30
max_request_size = 1048576
