chains:
  - name: ethereum
    rpc_url: https://65d1c7945fa54cfe8325e61562fe97f3-rpc.network.bloctopus.io/
    chain_id: 1
    deploy_core: false
  - name: arbitrum
    rpc_url: https://d88be824605745c0a09b1111da4727fd-rpc.network.bloctopus.io/
    chain_id: 42161
    deploy_core: false

agents:
  deployer:
    key: 0xDEPLOYER_PRIVATE_KEY
  relayer:
    key: 0xRELAYER_PRIVATE_KEY
    allow_local_checkpoint_syncers: true
  validators:
    - chain: ethereum
      signing_key: 0xVALIDATOR_PK_ETH
      checkpoint_syncer:
        type: local
        params:
          path: /validator-checkpoints
    - chain: arbitrum
      signing_key: 0xVALIDATOR_PK_ARB
      checkpoint_syncer:
        type: local
        params:
          path: /validator-checkpoints
  rebalancer:
    key: 0xREBALANCER_PRIVATE_KEY

warp_routes: []

global:
  registry_mode: public
  agent_image_tag: agents-v1.4.0
  cli_version: latest
