chains:
  - name: local1
    rpc_url: http://localhost:8545
    chain_id: 31337
    deploy_core: true
  - name: local2
    rpc_url: http://localhost:8546
    chain_id: 31338
    deploy_core: true

agents:
  deployer:
    key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
  relayer:
    key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    allow_local_checkpoint_syncers: true
  validators:
    - chain: local1
      signing_key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      checkpoint_syncer:
        type: local
        params:
          path: /validator-checkpoints
    - chain: local2
      signing_key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      checkpoint_syncer:
        type: local
        params:
          path: /validator-checkpoints

warp_routes: []

send_test:
  enabled: false

global:
  registry_mode: local
  agent_image_tag: agents-v1.4.0
  cli_version: latest